#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "open-web-analytics"
name = "Open Web Analytics"
description.en = "Open source alternative to commercial tools such as Google Analytics"
description.fr = "Alternative open source aux outils commerciaux tels que Google Analytics"

version = "1.8.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-2.0"
website = "https://www.openwebanalytics.com/"
code = "https://github.com/Open-Web-Analytics/Open-Web-Analytics"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso =false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/owa"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases/download/1.8.1/owa_1.8.1_packaged.tar"
    sha256 = "b33ac868d14d8b3aea7aa8e6382de9cf3f7acf0f340b932bd9fa2db4b7563d04"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-mysqli"

    [resources.database]
    type = "mysql"
